# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.6
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      # - uses: actions/checkout@v3
      # - uses: pnpm/action-setup@v2
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '18.x'
      #     cache: 'pnpm'
      # - run: pnpm install
      # - run: pnpm test
      # - uses: actions/checkout@v3
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     # node-version: ${{ matrix.node-version }}
      #     node-version: '18.x'
      #     cache: 'pnpm'
      # - run: npm install -g pnpm
      # - run: pnpm i
      # - run: pnpm test
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
